# Use YAML for configuration since it allows comments like this
site_name: CATHY days 2026
description: CATHY days 2026 website
author: Benjamin Mary
language: en
repository: CATHY-Org/CATHY_days_2023
favicon: images/sphx_glr_pyCATHY_weilletal_thumb.png
logo: images/Camporese_WRR_10.1029_2019WR025726.png
menu:
  - [Home, index]  
  - [About, about]
  - [Agenda, agenda] 
  - [<font color="blue"> Gallery </font>, gallery]  
  - [FAQ, FAQ]   
ignore:
  - README.md
  - config-alternative.json
  - Makefile
keywords: 'Catchment Hydrology'
language: en

